### ISSUE TITLE
"No combo-list found. Add one, and name it 'netflix' before starting the program. Ending."

### ISSUE THREAD

**Issue by SanctumDelete** [g3th/Netflix-Checker#5]
I tried it on Linux and W10. I tried to adjust it with encoding='utf-8' and it also didn't find the file, even though it was named according to the 'readme'

**Comment by g3th** [comment]
I can't replicate the issue in my VBOX. I have provided a short video to illustrate that the program works (using Debian):

https://streamable.com/50b8j2

Make sure your combo-list is named "netflix" only, not "netflix.txt." 
Make sure the file is in the correct folder. 
Moreover, 'extensions for known file types' might be disabled in your version of Windows, and you might need to enable them in order to see them.
